### PR TITLE
fix(go): query parameter of type enum array not properly serialized

### LINKED ISSUE #82: Query parameter of type Enum array is not properly serialized
**Describe the bug**
A query parameter of type Enum array is not properly serialized in CSV format.

**Where did you find this bug?**
 - [ ] ApiError Package 
 - [x] Https Package
 - [ ] TestHelper Package
 - [ ] Utilities Package
 - [ ] Not sure

**Expected behavior**
A query parameter of type Enum array should be properly serialized in CSV format.

**To Reproduce**
Steps to reproduce the bug:
1. serialize a query parameter in CSV format of type enum array. 

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Library version number**
For example:  0.0.21

**Environmental details**
For example:
OS: Any
Runtime version: GO 1.18

**Additional context**
https://friendsofapimatic.slack.com/archives/C05H44A59PW/p1717663000080119

### PR DESCRIPTION
**Pull request by haseeb-mhr**
## What
This PR contains changes to fix the query parameters of type Enum array to serialized in CSV format.

## Why
These changes are made to fix the bug reported by our customer.
Closes #82 

## Type of change
Select multiple if applicable.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause a breaking change)
- [ ] Tests (adds or updates tests)
- [ ] Documentation (adds or updates documentation)
- [ ] Refactor (style improvements, performance improvements, code refactoring)
- [ ] Revert (reverts a commit)
- [ ] CI/Build (adds or updates a script, change in external dependencies)

## Dependency Change
If a new dependency is being added, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Policy-of-adding-new-dependencies-in-the-core-libraries

## Breaking change
No breaking changes are introduced.

## Testing
List the steps that were taken to test the changes

## Checklist
- [ ] My code follows the coding conventions
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added new unit tests

### CODE REVIEW

File: https/formData.go [hunk 1]
```diff
@@ -207,6 +203,21 @@ func (fp *formParam) processSlice() (map[string][]string, error) {
 	return result, nil
 }
 
+func initIndexString(elem reflect.Value, index int) any {
```
Comment (Shield-Jaguar) [inline https/formData.go:206]: this looks like unreadable code. can you please refactor this one?

**Review by Shield-Jaguar — CHANGES_REQUESTED** [review]

File: https/formData.go (hunk 1 above)
Comment (haseeb-mhr) [reply https/formData.go]: Done refactoring to make it readable.

File: https/formData.go [hunk 2]
```diff
@@ -207,6 +203,25 @@ func (fp *formParam) processSlice() (map[string][]string, error) {
 	return result, nil
 }
 
+// creates index for enums and native types in slice
+func createElemIndex(elem reflect.Value, index int) any {
```
Comment (asadali214) [inline https/formData.go:207]: @haseeb-mhr This function's name/description and functionality is contradicting.

Its basically returning index for non scalar elements only, and otherwise nil. Can you name it like `getNonScalerElemIndex`, you can similarly update the description.

**Review by asadali214 — APPROVED** [review]

**Review by Shield-Jaguar — APPROVED** [review]
